# Generated by Django 4.0.6 on 2022-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datefamily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datefamily',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datefamily',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
